# Generated by Django 5.1.4 on 2025-01-02 06:46

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='CourseApp.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات دوره')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان دوره')),
                ('video_count', models.PositiveIntegerField(verbose_name='تعداد ویدیوها')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت دوره')),
                ('discount', models.SmallIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('is_paid', models.CharField(choices=[('free', 'رایگان'), ('premium', 'پولی')], default='premium', max_length=10, verbose_name='آیا دوره پولی است یا رایگان؟')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='عرض عکس حداکثر 600 پیکسل و ارتفاع عکس حداکثر 500 پیکسل باشد', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 500], upload_to='course_thumbnails/')),
                ('level', models.CharField(choices=[('introductory', 'سطح مقدماتی'), ('advanced', 'سطح پیشرفته'), ('introductory_advanced', 'سطح از مقدماتی تا پیشرفته')], default='introductory', max_length=30, verbose_name='سطح دوره')),
                ('course_status', models.CharField(choices=[('completed', 'تکمیل شده'), ('in_progress', 'درحال برگزاری'), ('starting_soon', 'شروع به زودی')], default='in_progress', max_length=20, verbose_name='وضعیت دوره')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='آیا دوره، پیشنهادی است؟')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ManyToManyField(to='CourseApp.category', verbose_name='دسته بندی')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان فصل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سوال')),
                ('description', models.TextField(verbose_name='جواب سوال')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب سوال و جواب ها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان ویدیو')),
                ('video_link', models.URLField(verbose_name='لینک ویدیو')),
                ('thumbnail', models.ImageField(blank=True, help_text='ارتفاع عکس: 500 پیکسل', null=True, upload_to='video_thumbnails/', verbose_name='تصویر دوره')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='ترتیب ویدیو')),
                ('is_paid', models.BooleanField(default=False, verbose_name='آیا برای دیدن نیاز به خرید دوره است؟')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان ویدیو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.chapter', verbose_name='فصل مربوطه')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
    ]
