# Generated by Django 5.1.4 on 2025-01-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(max_length=500, verbose_name='لینک ویدیو'),
        ),
    ]
