# Generated by Django 5.1.4 on 2025-01-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_alter_video_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='CourseApp.category', verbose_name='دسته بندی'),
        ),
    ]
